### PR TITLE
[ADD] error_pages: 400, 401, 403, 404, 500

### PR DESCRIPTION
**Pull request by tomeyro**
So @ruiztulio here is my proposal for the error pages. It is a simple design with a smooth background and text contrast. The highlight color could is adaptable to the website that it's going to be implemented on, and any dark color would work. The links in every page could also change according to the website. It also displays in the bottom that the website was made by Vauxoo. It's simple, funny and the message is easyly understandable.

1. Solid color emojis: the color adapts to the page.
image
2. Colored emojis: the colors are fixed but it looks cleaner.
image
3. Girl: It's still funny but a bit more serious (although not that much)
image
4. Cat: So cute!
image

- What do you think about the general design? (Minus the emojis)
- What do you think of the emojis? Idk if the error pages should be more/less serious.
- What do you think about the information/text/links? (I _tried_ to be a little funny with those)

NOTE: All images shown are free to use but require attribution in some form so we can use them.

NOTE 2: This MR was made using a branch that contains only the solid color emojis. Each of the proposal images has its own branch.

### CODE REVIEW

**Comment by nhomar** [comment]
I love it.

**Comment by ruiztulio** [comment]
@tomeyro I like more the 1, It have the Vauxoo's colours. Perhaps in the 500 page you could put the status link a little more visible.

But I like the general design, it's simple and funny. Good job!

**Comment by tomeyro** [comment]
@nhomar I'm glad you liked it.

@ruiztulio Ok, I will make the status link stand out a bit more. I like those icons too because they adapt to the website, and you mention that this will not be only for Vauxoo but also for Vauxoo's clients. And btw, taking that into account, what do you think about making a script and building this using html/css preprocessors? maybe jade/less? I could make a script that generates the error pages with cutomized colors and links using a config file.

**Comment by ruiztulio** [comment]
@tomeyro I like the idea, but the idea with this repo is to have these pages as simple as possible and if the customer wants a personalized page we can create another branch in the main repo only for them. Anyway, just do it for the colour scheme by now, then if we see any chance to enhance this we can go further

**Comment by tomeyro** [comment]
@ruiztulio 

So now the status link is underlined and bolder. I didn't know what else to do with it because I don't like it alone in a different line or bigger. The way it is now it looks good and stands out. Do you like it like this? Or what do you think would look better?

image

Also I organized the code better, and created a build script that generates the css and html (I know you told me not to do this right now but it wasn't going to take me much to do it, so I did) using [pug](http://pugjs.org/) for html and [less](http://lesscss.org/) for css.

For html, it reads from a json file the data for each page and generates them according to their names and locations:

image

For example: in the image above you can see that it will generate a 40x/400.html page, with the contents shown in the object.

For css it compiles a less file, which contains a couple of style vars:

image

If you change the values you can adjust the theme and get something like this:

image

image

Note that I updated the readme file to show how to build the pages.

**Comment by ruiztulio** [comment]
@tomeyro I'm down with this...can you update the readme and leave a little documentation there on where to change, how run it and so.

**Comment by tomeyro** [comment]
Done @ruiztulio

**Pull request merged**
