### PR TITLE
[FIX] error_pages: change image for any type of error on BF page

### PR DESCRIPTION
**Pull request by andreaarce**
Change the image of the error pages

### CODE REVIEW

**Comment by oscarolar** [comment]
@andreaarce todo parece correcto, ¿podrías poner screenshots de las páginas por favor (que se vea la URL)?

**Comment by andreaarce** [comment]
@oscarolar 

**40x Pages**

400


401


403


404


**50x Pages**

500

**Comment by oscarolar** [comment]
@ruiztulio this is good to go, can you merge and do your thing?

**Comment by ruiztulio** [comment]
@oscarolar @andreaarce Done, it is also deployed in the server:

a

**Pull request merged**
